male_names = ["Zy'sax", "Davdaran", "Galrax", "Pargeroz", "Rodred", "Taroth", "Cru'gom", "Burro'tzor", "Fumor",
              "Antarah", "Ezfar", "Barbalek", "Chenfar", "Rogrim", "Guramon", "Kurmin", "Kraarax", "Anthac", "Onai",
              "'ryon", "Furtrax", "Grazakos", "Zythac", "Urkranath", "Arlas", "Bagrim", "Festerross", "Sathugarr",
              "Burrostix", "Kurgan", "Devbar", "Bruroq", "Furand", "Zaram", "Ygarah", "Putrius", "Asrus", "Purigax",
              "Kasso'tzor", "Skynacus", "Dy'sax", "Crufar", "Devban", "Goulgax", "Pumon", "Kasso'lumin", "Guraphoz",
              "Sekrax", "Mortedon", "Aszar", "Ingusalax", "Pho'gaz", "Anu'tiro", "Onaifar", "Ekuraz", "Luross",
              "Galrand", "Eztoth", "Estophoz", "Abrubar", "Varban", "Ahrumek", "Svoghast", "Bafar", "Zhosalax",
              "Baltagan", "Festerlax", "Urkrazar", "Bero'gom", "Kumus", "Morde'palos", "Onairaz", "Purigore",
              "Khroghast", "Drachdon", "Endekai", "Kakhar", "Vubhor", "Estorouth", "Garagor", "Estorhaz", "Anusour",
              "Abrumon", "Asram", "Burro'palos", "Rhyvile", "Hon'sax", "Kyrak", "Demaruman", "Morterah", "Azudred",
              "Omphuthor", "Kassolek", "Kraabar", "Skygar", "Tudon", "Guragral", "Kamus", "Khro'lumin", "Furraz",
              "Drachdekai", "Arlas", "Inguban", "Elarass", "Antathral", "Marhaz", "Mephifar", "Grazalock", "Fudaran",
              "Jurumor", "Khatrius", "Caorpu'tiro", "Urka'ryon", "Titatrius", "Abrufar", "Abrugan", "Hourolath",
              "Davgral", "Elarah", "Titanok", "Enrulak", "Zhuthac", "Zaneus", "Khro'gaz", "Rharulak", "Buldagrim",
              "Davnaer", "Halalaz", "Barbadaran", "Tatrius", "Sekphus", "Guraphoz", "Jitoth", "Mortenux", "Festerfar",
              "Farnon", "Eredred", "Kyrouth", "Abrudax", "Pargetrax", "Karoz", "Fugax", "Kurnath", "Anu'sax",
              "Anuruman", "Festerroq", "Onaiphoz", "Davvax", "Jiphus", "Burrodiaz", "Marah"]

female_names = ["Dreshthis", "Estarique", "Kynesh", "Enemuse", "Balagenn", "Dreshvie", "Chesresh", "Maruxa", "Logrell",
                "Henpho", "Rhiarhazi", "Ingepho", "Fesbise", "Rhynosa", "Asgash", "Gayabise", "Abineuth", "Grisathall",
                "Pergehirr", "Kezruse", "Rhiarhazi", "Ingepho", "Fesbise", "Rhynosa", "Asgash", "Gayabise", "Abineuth",
                "Grisathall", "Pergehirr", "Kezruse", "Ezkei", "Puridynn", "Hezdash", "Sivagwer", "Uraprix", "Uradynn",
                "Fyzara", "Asreon", "Kezbhox", "Hezzara", "Nasusty", "Jidex", "Abithess", "Carithall", "Dev'gah",
                "Angihr", "Madine", "Crydresh", "Verdehk", "Khaahirr", "Berrosty", "Melgwer", "Zhorane", "Galriyes",
                "Jivix", "Galgaer", "Jinosa", "Esta'lith", "Gayabine", "Bri'khas", "Gayadynn", "Enezara", "Nemedex",
                "Fygrinn", "Hengoye", "Skidarah", "Telogihr", "Telobara", "Tiyabis", "Anmuse", "Unadash", "Ophu'lumix",
                "Bridash", "Morebess", "Sivamorta", "Berba'tira", "Thabise", "Unaliz", "Gayakiz", "Helasilix",
                "Urlidiaz", "Belobise", "Sephugenn", "Sehkrothe", "Helamuse", "Arhiliz", "Juranosa", "Onipho",
                "Abrebara", "Helarenne", "Chesdine", "Devneth", "Uraruxa", "Vugaer", "Giraroze", "Golriyes", "Elasilix",
                "Hoagwer", "Molek", "Bagrell", "Baliz", "Purithall", "Bala'khas", "Ahnumuse", "Asnihx", "Golgwer",
                "Anadynn", "Galvie", "Rhy'ginn", "Yabise", "Purinosa", "Zhokiz", "Krebis", "Zyruse", "Aranihx", "Gikiz",
                "Liriss", "Ophutriesh", "Cryneuth", "Roleck", "Elathia", "Ahnudehk", "Balarothe", "Zylek", "Demaneth",
                "Urlireon", "Berro'gah", "Nasuruxa", "Lonu", "Melbise", "Pigenn", "Juraless", "Azurique", "Zoethis",
                "Telorane", "Urabara", "Mordephis", "Elaress", "Fihrthia", "Kashu'yah", "Helaneuth", "Zoerane",
                "Melbara", "Ekimuse", "Festhess", "Devneth", "Elytrix", "Zoesilix", "Sivathis", "Ophuthall", ]

